# Authors: Denis Engemann <denis.engemann@gmail.com>
#          Danilo Bzdok <danilobzdok@gmail.com>
#
# License: BSD (3-clause)

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from mpl_toolkits.axes_grid.inset_locator import inset_axes
from mpl_toolkits.axes_grid1 import make_axes_locatable

df = pd.read_pickle('./simulations.gzip')

df.model_violation[df.model_violation.isnull()] = 'None'

pvals = np.array([x for x in df['lr_pvalues'].values])

scores = np.array([x for x in df['scores_debiased'].values])

scores_ = scores.max(-1)
scores_[scores_ < 0] = 0

pvals_ = pvals.min(1)

sns.set_style('ticks')

plt.close('all')

titles = [
    'Generated by true model',
    'Polynomially transformed',
    'Corruption with noise',
    'Correlation strength',
    'Sample size',
    'Relevant variables'
]

cases = [
    'model',
    'poly',
    'noise',
    'correlation',
    'sample size',
    'prop rel'
]

cbar_label = [
    'True model',
    'Poly degree',
    'Noise factor',
    'Correlation',
    'Sample size',
    'Prop. relevant'
]

data_index = {
    'model': np.arange(len(df)),
    'poly': df.model_violation.str.contains('\^').values,
    'noise': np.arange(len(df)),
    'correlation': np.arange(len(df)),
    'sample size': np.arange(len(df)),
    'prop rel': np.arange(len(df)),
}

plt.close('all')
fig, axes = plt.subplots(2, 3, figsize=(9, 5), sharey=True)

n_samp = df.n_samples
axes = axes.ravel()
for ii, case in enumerate(cases):

    ax = axes[ii]
    inds = data_index[case]
    x, y = -np.log10(pvals_[inds]), scores_[inds]

    color = df.n_feat_relevant.values[inds]
    # size = (np.log10(df.n_samples.values[inds]) ** 2)

    ax.grid(True)
    if case == 'model':
        cvals = (df.model_violation != 'None').values.astype(int)
    elif case == 'poly':
        cvals = np.array([
            int(x.split('^')[-1]) for x in
            df.model_violation.values[inds] if '^' in x])
    elif case == 'noise':
        cvals = df.noise.values
    elif case == 'correlation':
        cvals = np.zeros(len(df))
        cvals[df.corr_strength == .5] = 0.5
        cvals[df.corr_strength == .9] = 0.9
    elif case == 'sample size':
        cvals = np.log10(df.n_samples).values
    elif case == 'prop rel':
        cvals = (df.n_feat_relevant / 40.).values
    else:
        raise ValueError('No no no.')

    scat = ax.scatter(x, y, c=cvals,
                      s=2,
                      edgecolors='face',
                      cmap=plt.get_cmap('viridis', len(np.unique(cvals))),
                      alpha=0.1)

    divider = make_axes_locatable(ax)
    cax = divider.append_axes('right', size='5%', pad=0.3)

    cticks = np.unique(cvals)
    cb = fig.colorbar(scat, cax=cax, orientation='vertical',
                      ticks=cticks[[0, -1]])
    cb.set_alpha(1)
    cb.draw_all()
    cax.yaxis.set_label_position('left')
    if case == 'sample size':
        cb.set_ticklabels(10 ** cticks[[0, -1]])
    elif case == 'model':
        cb.set_ticklabels(['no', 'yes'])
    cb.set_label(cbar_label[ii], fontsize=14, fontweight=100)

    ax.set_xlim(-1, 305)
    ax.set_xticks([0, 100, 200, 300])

    ax.set_ylim(-0.05, 1.05)
    ax.set_yticks([
        0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.9, 0.8, 1.0])
    ax.set_title(titles[ii])
    ax.axvline(-np.log10(0.05), color='red', linestyle='--')

    ax_inset = inset_axes(
        ax, width="30%",
        height="30%",
        loc=4,
        bbox_to_anchor=(0, 0.1, 1, 1.1),
        bbox_transform=ax.transAxes)
    scat = ax_inset.scatter(x, y,
                            c=cvals,
                            cmap=plt.get_cmap('viridis',
                                              len(np.unique(cvals))),
                            s=2,
                            edgecolors='face',
                            vmin=0.2,
                            alpha=0.1)
    ax_inset.set_xlim(*-np.log10([0.5, 0.001]))
    ax_inset.set_xticks(
        -np.log10([0.5, 0.4, 0.3, 0.2, 0.1, 0.05, 0.01, 0.01, 0.001]))
    ax_inset.set_ylim(-0.05, 1.05)
    ax_inset.axvline(
        -np.log10(0.05), color='red', linestyle='--')
    pvals_orig = (10 ** (-1 * ax_inset.get_xticks())).round(3)
    ax_inset.set_xticklabels([
        str(ll) if ii in [0, len(pvals_orig) - 1]
        else '' for ii, ll in enumerate(pvals_orig)], color='#383838')
    ax_inset.set_yticklabels(['', 0, 1, ''], color='#383838')
    sns.despine(trim=True, ax=ax)

    if ii > 2:
        ax.set_xlabel(r'$-log_{10}(p)$', fontsize=10, fontweight=150)
    if ii in (0, 3):
        ax.set_ylabel(r'prediction [$R^2$]',
                      fontsize=12, fontweight=150)

plt.subplots_adjust(hspace=0.33, wspace=.46, left=.12, right=.90, top=.94,
                    bottom=.10)
plt.savefig('./figures/simulations_by_aspect.png', bbox_inches='tight',
            dpi=300)
